#!/bin/bash

if [[ ! -z "$DOKKU_DEV" ]]; then
  export DOKKU_DEV=true
  export DOKKU_ROOT=/home/dokku

  chmod +x commands
  chmod +x install
  chmod +x dockerfiles/bin/manage

  ./commands redis:stop

  docker rmi ohardy/redis
  rm -rf /home/dokku/.o_redis
  docker build --no-cache -t ohardy/redis dockerfiles/

  ./install
fi
